name: Build and Push Docker Image to GHCR

on:
  schedule:
    # Runs every Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get next version
        id: version
        uses: reecetech/version-increment@2024.10.1
        with:
          scheme: semver
          increment: patch

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .  # Path to the directory containing the Dockerfile
          push: true  # Push the image to GHCR
          platforms: linux/arm64 # Build for Macs
          tags: ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }} # Use a semantic versioning strategy to bump the version
